const fetch = require('node-fetch');
const cloudinary = require('cloudinary').v2;

/**
 * GEMINI (IMAGEN) ADAPTER
 * 
 * CRITICAL: Gemini DOES NOT accept image URLs
 * MUST download Cloudinary images and convert to base64
 */
class GeminiAdapter {
    constructor(apiKey, model = 'imagen-3.0-generate-001') {
        this.apiKey = apiKey;
        this.model = model;
        this.baseUrl = 'https://generativelanguage.googleapis.com/v1beta';
    }

    /**
     * Download image from Cloudinary URL and convert to base64
     */
    async downloadAndConvertToBase64(imageUrl) {
        try {
            const response = await fetch(imageUrl);
            if (!response.ok) throw new Error(`Failed to download image: ${response.statusText}`);

            const buffer = await response.buffer();
            const base64 = buffer.toString('base64');
            const mimeType = response.headers.get('content-type') || 'image/jpeg';

            return { base64, mimeType };
        } catch (error) {
            throw new Error(`Image download failed: ${error.message}`);
        }
    }

    /**
     * Generate image using Gemini Imagen
     * Accepts Cloudinary URLs but converts to base64 internally
     */
    async generate({ prompt, referenceImages = [], aspectRatio = '1:1', negativePrompt = '' }) {
        try {
            // Process reference images - Download and convert to base64
            const imageParts = [];
            for (const imageUrl of referenceImages) {
                const { base64, mimeType } = await this.downloadAndConvertToBase64(imageUrl);
                imageParts.push({
                    inline_data: {
                        mime_type: mimeType,
                        data: base64
                    }
                });
            }

            // Build request payload
            const requestBody = {
                contents: [
                    {
                        parts: [
                            ...imageParts,
                            { text: prompt }
                        ]
                    }
                ],
                generationConfig: {
                    aspectRatio: aspectRatio,
                    negativePrompt: negativePrompt,
                    numberOfImages: 1,
                    safetyFilterLevel: 'block_some',
                    personGeneration: 'allow_adult'
                }
            };

            // Call Gemini API
            const response = await fetch(
                `${this.baseUrl}/models/${this.model}:generateImages?key=${this.apiKey}`,
                {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(requestBody)
                }
            );

            if (!response.ok) {
                const error = await response.json();
                throw new Error(`Gemini API Error: ${JSON.stringify(error)}`);
            }

            const result = await response.json();

            // Extract generated image (base64)
            const generatedImageBase64 = result.predictions?.[0]?.bytesBase64Encoded;
            if (!generatedImageBase64) {
                throw new Error('No image generated by Gemini');
            }

            // Convert base64 to buffer for upload
            const imageBuffer = Buffer.from(generatedImageBase64, 'base64');

            // Upload to Cloudinary (Account 3)
            const cloudinaryUrl = await this.uploadToCloudinary(imageBuffer);

            return {
                success: true,
                imageUrl: cloudinaryUrl,
                provider: 'gemini'
            };

        } catch (error) {
            console.error('Gemini Adapter Error:', error);
            throw error;
        }
    }

    /**
     * Upload generated image to Cloudinary
     */
    async uploadToCloudinary(imageBuffer) {
        return new Promise((resolve, reject) => {
            const uploadStream = cloudinary.uploader.upload_stream(
                {
                    folder: 'generations',
                    resource_type: 'image',
                    public_id: `gemini_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
                },
                (error, result) => {
                    if (error) reject(error);
                    else resolve(result.secure_url);
                }
            );
            uploadStream.end(imageBuffer);
        });
    }
}

module.exports = GeminiAdapter;
