const fetch = require('node-fetch');
const cloudinary = require('cloudinary').v2;
const FormData = require('form-data');

/**
 * STABILITY AI (SDXL) ADAPTER
 * 
 * Accepts Cloudinary URLs directly for image-to-image
 */
class StabilityAdapter {
    constructor(apiKey, model = 'stable-diffusion-xl-1024-v1-0') {
        this.apiKey = apiKey;
        this.model = model;
        this.baseUrl = 'https://api.stability.ai/v1/generation';
    }

    /**
     * Generate image using Stability AI (SDXL)
     * Sends Cloudinary URL as init_image
     */
    async generate({ prompt, referenceImages = [], strength = 0.35, negativePrompt = '' }) {
        try {
            // Use first reference image as init_image
            let initImageBuffer = null;
            if (referenceImages && referenceImages.length > 0) {
                // Download reference image from Cloudinary
                const imageResponse = await fetch(referenceImages[0]);
                if (!imageResponse.ok) {
                    throw new Error('Failed to download reference image');
                }
                initImageBuffer = await imageResponse.buffer();
            }

            // Build form data
            const formData = new FormData();
            formData.append('text_prompts[0][text]', prompt);
            formData.append('text_prompts[0][weight]', '1');

            if (negativePrompt) {
                formData.append('text_prompts[1][text]', negativePrompt);
                formData.append('text_prompts[1][weight]', '-1');
            }

            formData.append('cfg_scale', '7');
            formData.append('samples', '1');
            formData.append('steps', '30');

            // If we have init image, use image-to-image
            if (initImageBuffer) {
                formData.append('init_image', initImageBuffer, {
                    filename: 'init.png',
                    contentType: 'image/png'
                });
                formData.append('image_strength', strength.toString());
            }

            // Determine endpoint
            const endpoint = initImageBuffer
                ? `${this.baseUrl}/${this.model}/image-to-image`
                : `${this.baseUrl}/${this.model}/text-to-image`;

            // Call Stability AI API
            const response = await fetch(endpoint, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${this.apiKey}`,
                    'Accept': 'application/json',
                    ...formData.getHeaders()
                },
                body: formData
            });

            if (!response.ok) {
                const error = await response.json();
                throw new Error(`Stability API Error: ${JSON.stringify(error)}`);
            }

            const result = await response.json();

            // Extract base64 image
            const generatedImageBase64 = result.artifacts?.[0]?.base64;
            if (!generatedImageBase64) {
                throw new Error('No image generated by Stability AI');
            }

            // Convert base64 to buffer
            const imageBuffer = Buffer.from(generatedImageBase64, 'base64');

            // Upload to Cloudinary (Account 3)
            const cloudinaryUrl = await this.uploadToCloudinary(imageBuffer);

            return {
                success: true,
                imageUrl: cloudinaryUrl,
                provider: 'stability'
            };

        } catch (error) {
            console.error('Stability Adapter Error:', error);
            throw error;
        }
    }

    /**
     * Upload generated image to Cloudinary
     */
    async uploadToCloudinary(imageBuffer) {
        return new Promise((resolve, reject) => {
            const uploadStream = cloudinary.uploader.upload_stream(
                {
                    folder: 'generations',
                    resource_type: 'image',
                    public_id: `stability_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
                },
                (error, result) => {
                    if (error) reject(error);
                    else resolve(result.secure_url);
                }
            );
            uploadStream.end(imageBuffer);
        });
    }
}

module.exports = StabilityAdapter;
